### ISSUE TITLE
IOS application "Pythonista"

### ISSUE THREAD

**Issue by nick-fullstack-dev** [wcomartin/kiauvo#2]
Hello,
I live in Canada, with the harsh winters, starting and pre-heating the vehicle is a real comfort.
Is it possible to make this code compatible with the IOS application "Pythonista" in order to use it with the IOS shortcuts of the iPhone?
Example an IOS shortcut to perform a custom start of the car 10 minutes before leaving work in the evening or before leaving home in the morning.
I don't feel comfortable with Python, to make corrections.
Thanks

**Comment by PierreLevres** [comment]
Isn't the UVO app doing exactly that for you? Preheating the car etc??

**Comment by nick-fullstack-dev** [comment]
> Isn't the UVO app doing exactly that for you? Preheating the car etc??

Thank you for your reply.
Yes, but only in manual mode. I have to launch the UVO application manually and enter my PIN (or face-id), then execute the startup.
To automate this action would be great.
I know that the "shortcuts" feature official and "Home" of iOS allows to launch python scripts which are executed by the "Pythonista" application. It would even be possible to start the vehicle using Siri
Thanks

**Comment by wcomartin** [comment]
I'm sorry I would have no idea how to test that, I don't own any iOS devices. 
Feel free to create a fork or a script that can do that for you.
